/**
  *APIMATICCalculatorLib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
  */


angular.module('APIMATICCalculatorLib').factory('OperationTypeEnum', function() {
    return {
   
     //Represents the sum operator
    
    SUM : "SUM",

   
     //Represents the subtract operator
    
    SUBTRACT : "SUBTRACT",

   
     //Represents the multiply operator
    
    MULTIPLY : "MULTIPLY",

   
     //Represents the divide operator
    
    DIVIDE : "DIVIDE",

    };
});